DROP TABLE IF EXISTS source CASCADE;
DROP TABLE IF EXISTS keyword_set CASCADE;
DROP TABLE IF EXISTS nogo_rule CASCADE;
DROP TABLE IF EXISTS target_criteria CASCADE;
DROP TABLE IF EXISTS company_profile CASCADE;
